main : main.o tableau.o structure.o
	gcc -o main main.o tableau.o structure.o

main.o : main.c
	gcc -c -o main.o main.c

tableau.o : tableau.c
	gcc -c -o tableau.o tableau.c

structure.o : structure.c
	gcc -c -o structure.o structure.c

